import ErdosattackM.Correct
/-!
# The 28 minimal-order non-log-concave trees, certified semantically

Generated by `gen_witnesses_rt.py` from the census files in `../p993/`
(2 trees on 26 vertices, 19 on 28, 7 on 29). Each tree is given as a rose-tree
(`RT`) literal; `decide` recomputes its independence polynomial in the kernel,
and `indepPolyRT_correct` (proved in `ErdosattackM/Correct.lean`) upgrades the
coefficients to actual counts of independent vertex subsets. The `_toEdges`
theorems certify that each rose tree flattens to exactly the edge list used by
the mathlib-free core package (`lean/Erdosattack/Witnesses.lean`).
-/

namespace ErdosattackM

/-- Witness 1 on 26 vertices (T_{3,4,4} (Kadrawi-Levit)), as a rose tree. -/
def t26_1 : RT := .node [.node [.node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]]]

/-- Census coefficient list of `t26_1`. -/
def c26_1 : List Nat := [1, 26, 300, 2040, 9142, 28551, 63933, 103736, 121376, 100144, 55499, 18683, 2979, 51, 1]

theorem t26_1_poly : indepPolyRT t26_1 = c26_1 := by decide

/-- `t26_1` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w26_1`. -/
theorem t26_1_toEdges : t26_1.toEdges = (26, [(25, 24), (24, 19), (23, 22), (22, 19), (21, 20), (20, 19), (19, 0), (18, 17), (17, 10), (16, 15), (15, 10), (14, 13), (13, 10), (12, 11), (11, 10), (10, 0), (9, 8), (8, 1), (7, 6), (6, 1), (5, 4), (4, 1), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t26_1` has exactly `c26_1[k]` independent sets of size `k`. -/
theorem t26_1_counts (k : Nat) : t26_1.indepCount k = c26_1.getD k 0 := by
  rw [← indepPolyRT_correct, t26_1_poly]

theorem t26_1_nlc : NLCAt t26_1.indepCount 13 := by
  unfold NLCAt; simp only [t26_1_counts]; decide

theorem t26_1_unimodal : UnimodalAt t26_1.indepCount 8 := by
  rw [funext t26_1_counts]
  exact unimodalAt_getD c26_1 8 (by decide) (by decide)

theorem t26_1_good : GoodTree t26_1 c26_1 13 8 :=
  ⟨t26_1_counts, t26_1_nlc, t26_1_unimodal⟩

/-- Witness 2 on 26 vertices (T*_{3,3,4} (Kadrawi-Levit)), as a rose tree. -/
def t26_2 : RT := .node [.node [.node []], .node [.node []], .node [.node [.node [.node []]]], .node [.node [.node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]]]]

/-- Census coefficient list of `t26_2`. -/
def c26_2 : List Nat := [1, 26, 300, 2037, 9089, 28147, 62183, 98968, 112870, 90178, 48086, 15498, 2372, 48, 1]

theorem t26_2_poly : indepPolyRT t26_2 = c26_2 := by decide

/-- `t26_2` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w26_2`. -/
theorem t26_2_toEdges : t26_2.toEdges = (26, [(25, 24), (24, 0), (23, 22), (22, 0), (21, 20), (20, 19), (19, 18), (18, 0), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t26_2` has exactly `c26_2[k]` independent sets of size `k`. -/
theorem t26_2_counts (k : Nat) : t26_2.indepCount k = c26_2.getD k 0 := by
  rw [← indepPolyRT_correct, t26_2_poly]

theorem t26_2_nlc : NLCAt t26_2.indepCount 13 := by
  unfold NLCAt; simp only [t26_2_counts]; decide

theorem t26_2_unimodal : UnimodalAt t26_2.indepCount 8 := by
  rw [funext t26_2_counts]
  exact unimodalAt_getD c26_2 8 (by decide) (by decide)

theorem t26_2_good : GoodTree t26_2 c26_2 13 8 :=
  ⟨t26_2_counts, t26_2_nlc, t26_2_unimodal⟩

/-- Witness 1 on 28 vertices (T_{4,4,4} (KL family)), as a rose tree. -/
def t28_1 : RT := .node [.node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]]]

/-- Census coefficient list of `t28_1`. -/
def c28_1 : List Nat := [1, 28, 351, 2619, 13028, 45789, 117358, 222711, 313692, 324596, 240347, 120903, 37220, 5410, 60, 1]

theorem t28_1_poly : indepPolyRT t28_1 = c28_1 := by decide

/-- `t28_1` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_1`. -/
theorem t28_1_toEdges : t28_1.toEdges = (28, [(27, 26), (26, 19), (25, 24), (24, 19), (23, 22), (22, 19), (21, 20), (20, 19), (19, 0), (18, 17), (17, 10), (16, 15), (15, 10), (14, 13), (13, 10), (12, 11), (11, 10), (10, 0), (9, 8), (8, 1), (7, 6), (6, 1), (5, 4), (4, 1), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_1` has exactly `c28_1[k]` independent sets of size `k`. -/
theorem t28_1_counts (k : Nat) : t28_1.indepCount k = c28_1.getD k 0 := by
  rw [← indepPolyRT_correct, t28_1_poly]

theorem t28_1_nlc : NLCAt t28_1.indepCount 14 := by
  unfold NLCAt; simp only [t28_1_counts]; decide

theorem t28_1_unimodal : UnimodalAt t28_1.indepCount 9 := by
  rw [funext t28_1_counts]
  exact unimodalAt_getD c28_1 9 (by decide) (by decide)

theorem t28_1_good : GoodTree t28_1 c28_1 14 9 :=
  ⟨t28_1_counts, t28_1_nlc, t28_1_unimodal⟩

/-- Witness 2 on 28 vertices (T_{3,4,5} (KL family)), as a rose tree. -/
def t28_2 : RT := .node [.node [.node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []], .node [.node []]]]

/-- Census coefficient list of `t28_2`. -/
def c28_2 : List Nat := [1, 28, 351, 2620, 13046, 45931, 118008, 224630, 317521, 329839, 245228, 123878, 38310, 5606, 68, 1]

theorem t28_2_poly : indepPolyRT t28_2 = c28_2 := by decide

/-- `t28_2` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_2`. -/
theorem t28_2_toEdges : t28_2.toEdges = (28, [(27, 26), (26, 21), (25, 24), (24, 21), (23, 22), (22, 21), (21, 0), (20, 19), (19, 12), (18, 17), (17, 12), (16, 15), (15, 12), (14, 13), (13, 12), (12, 0), (11, 10), (10, 1), (9, 8), (8, 1), (7, 6), (6, 1), (5, 4), (4, 1), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_2` has exactly `c28_2[k]` independent sets of size `k`. -/
theorem t28_2_counts (k : Nat) : t28_2.indepCount k = c28_2.getD k 0 := by
  rw [← indepPolyRT_correct, t28_2_poly]

theorem t28_2_nlc : NLCAt t28_2.indepCount 14 := by
  unfold NLCAt; simp only [t28_2_counts]; decide

theorem t28_2_unimodal : UnimodalAt t28_2.indepCount 9 := by
  rw [funext t28_2_counts]
  exact unimodalAt_getD c28_2 9 (by decide) (by decide)

theorem t28_2_good : GoodTree t28_2 c28_2 14 9 :=
  ⟨t28_2_counts, t28_2_nlc, t28_2_unimodal⟩

/-- Witness 3 on 28 vertices (outside plain KL/KL* family), as a rose tree. -/
def t28_3 : RT := .node [.node [.node []], .node [.node []], .node [.node []], .node [.node [], .node [.node []]], .node [.node [.node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]]]]

/-- Census coefficient list of `t28_3`. -/
def c28_3 : List Nat := [1, 28, 351, 2617, 12988, 45439, 115589, 216970, 301151, 305881, 221498, 108674, 32663, 4725, 95, 2]

theorem t28_3_poly : indepPolyRT t28_3 = c28_3 := by decide

/-- `t28_3` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_3`. -/
theorem t28_3_toEdges : t28_3.toEdges = (28, [(27, 26), (26, 0), (25, 24), (24, 0), (23, 22), (22, 0), (21, 18), (20, 19), (19, 18), (18, 0), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_3` has exactly `c28_3[k]` independent sets of size `k`. -/
theorem t28_3_counts (k : Nat) : t28_3.indepCount k = c28_3.getD k 0 := by
  rw [← indepPolyRT_correct, t28_3_poly]

theorem t28_3_nlc : NLCAt t28_3.indepCount 14 := by
  unfold NLCAt; simp only [t28_3_counts]; decide

theorem t28_3_unimodal : UnimodalAt t28_3.indepCount 9 := by
  rw [funext t28_3_counts]
  exact unimodalAt_getD c28_3 9 (by decide) (by decide)

theorem t28_3_good : GoodTree t28_3 c28_3 14 9 :=
  ⟨t28_3_counts, t28_3_nlc, t28_3_unimodal⟩

/-- Witness 4 on 28 vertices (outside plain KL/KL* family), as a rose tree. -/
def t28_4 : RT := .node [.node [.node []], .node [.node []], .node [.node []], .node [.node [.node [.node []]]], .node [.node [.node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]]]]

/-- Census coefficient list of `t28_4`. -/
def c28_4 : List Nat := [1, 28, 351, 2616, 12969, 45282, 114842, 214690, 296459, 299246, 215076, 104537, 30997, 4356, 61, 1]

theorem t28_4_poly : indepPolyRT t28_4 = c28_4 := by decide

/-- `t28_4` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_4`. -/
theorem t28_4_toEdges : t28_4.toEdges = (28, [(27, 26), (26, 0), (25, 24), (24, 0), (23, 22), (22, 0), (21, 20), (20, 19), (19, 18), (18, 0), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_4` has exactly `c28_4[k]` independent sets of size `k`. -/
theorem t28_4_counts (k : Nat) : t28_4.indepCount k = c28_4.getD k 0 := by
  rw [← indepPolyRT_correct, t28_4_poly]

theorem t28_4_nlc : NLCAt t28_4.indepCount 14 := by
  unfold NLCAt; simp only [t28_4_counts]; decide

theorem t28_4_unimodal : UnimodalAt t28_4.indepCount 9 := by
  rw [funext t28_4_counts]
  exact unimodalAt_getD c28_4 9 (by decide) (by decide)

theorem t28_4_good : GoodTree t28_4 c28_4 14 9 :=
  ⟨t28_4_counts, t28_4_nlc, t28_4_unimodal⟩

/-- Witness 5 on 28 vertices (outside plain KL/KL* family), as a rose tree. -/
def t28_5 : RT := .node [.node [.node []], .node [.node [.node [.node []]]], .node [.node [.node [.node []]]], .node [.node [.node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]]]]

/-- Census coefficient list of `t28_5`. -/
def c28_5 : List Nat := [1, 28, 351, 2613, 12910, 44774, 112316, 206640, 279245, 274194, 190551, 89071, 25317, 3426, 56, 1]

theorem t28_5_poly : indepPolyRT t28_5 = c28_5 := by decide

/-- `t28_5` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_5`. -/
theorem t28_5_toEdges : t28_5.toEdges = (28, [(27, 26), (26, 0), (25, 24), (24, 23), (23, 22), (22, 0), (21, 20), (20, 19), (19, 18), (18, 0), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_5` has exactly `c28_5[k]` independent sets of size `k`. -/
theorem t28_5_counts (k : Nat) : t28_5.indepCount k = c28_5.getD k 0 := by
  rw [← indepPolyRT_correct, t28_5_poly]

theorem t28_5_nlc : NLCAt t28_5.indepCount 14 := by
  unfold NLCAt; simp only [t28_5_counts]; decide

theorem t28_5_unimodal : UnimodalAt t28_5.indepCount 8 := by
  rw [funext t28_5_counts]
  exact unimodalAt_getD c28_5 8 (by decide) (by decide)

theorem t28_5_good : GoodTree t28_5 c28_5 14 8 :=
  ⟨t28_5_counts, t28_5_nlc, t28_5_unimodal⟩

/-- Witness 6 on 28 vertices (outside plain KL/KL* family), as a rose tree. -/
def t28_6 : RT := .node [.node [.node []], .node [.node []], .node [.node [.node [.node []], .node [.node []]]], .node [.node [.node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]]]]

/-- Census coefficient list of `t28_6`. -/
def c28_6 : List Nat := [1, 28, 351, 2614, 12931, 44964, 113296, 209844, 286205, 284389, 200504, 95269, 27541, 3779, 59, 1]

theorem t28_6_poly : indepPolyRT t28_6 = c28_6 := by decide

/-- `t28_6` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_6`. -/
theorem t28_6_toEdges : t28_6.toEdges = (28, [(27, 26), (26, 0), (25, 24), (24, 0), (23, 22), (22, 19), (21, 20), (20, 19), (19, 18), (18, 0), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_6` has exactly `c28_6[k]` independent sets of size `k`. -/
theorem t28_6_counts (k : Nat) : t28_6.indepCount k = c28_6.getD k 0 := by
  rw [← indepPolyRT_correct, t28_6_poly]

theorem t28_6_nlc : NLCAt t28_6.indepCount 14 := by
  unfold NLCAt; simp only [t28_6_counts]; decide

theorem t28_6_unimodal : UnimodalAt t28_6.indepCount 8 := by
  rw [funext t28_6_counts]
  exact unimodalAt_getD c28_6 8 (by decide) (by decide)

theorem t28_6_good : GoodTree t28_6 c28_6 14 8 :=
  ⟨t28_6_counts, t28_6_nlc, t28_6_unimodal⟩

/-- Witness 7 on 28 vertices (T*_{3,4,4} (KL* family)), as a rose tree. -/
def t28_7 : RT := .node [.node [.node []], .node [.node []], .node [.node [.node [.node []]]], .node [.node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]]]]

/-- Census coefficient list of `t28_7`. -/
def c28_7 : List Nat := [1, 28, 351, 2616, 12969, 45281, 114827, 214595, 296124, 298522, 214089, 103703, 30592, 4264, 57, 1]

theorem t28_7_poly : indepPolyRT t28_7 = c28_7 := by decide

/-- `t28_7` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_7`. -/
theorem t28_7_toEdges : t28_7.toEdges = (28, [(27, 26), (26, 0), (25, 24), (24, 0), (23, 22), (22, 21), (21, 20), (20, 0), (19, 18), (18, 11), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_7` has exactly `c28_7[k]` independent sets of size `k`. -/
theorem t28_7_counts (k : Nat) : t28_7.indepCount k = c28_7.getD k 0 := by
  rw [← indepPolyRT_correct, t28_7_poly]

theorem t28_7_nlc : NLCAt t28_7.indepCount 14 := by
  unfold NLCAt; simp only [t28_7_counts]; decide

theorem t28_7_unimodal : UnimodalAt t28_7.indepCount 9 := by
  rw [funext t28_7_counts]
  exact unimodalAt_getD c28_7 9 (by decide) (by decide)

theorem t28_7_good : GoodTree t28_7 c28_7 14 9 :=
  ⟨t28_7_counts, t28_7_nlc, t28_7_unimodal⟩

/-- Witness 8 on 28 vertices (outside plain KL/KL* family), as a rose tree. -/
def t28_8 : RT := .node [.node [.node [.node [.node []]]], .node [.node [.node [.node []]]], .node [.node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]]]]

/-- Census coefficient list of `t28_8`. -/
def c28_8 : List Nat := [1, 28, 351, 2614, 12929, 44929, 113029, 208679, 283002, 278640, 193781, 90347, 25504, 3415, 55, 1]

theorem t28_8_poly : indepPolyRT t28_8 = c28_8 := by decide

/-- `t28_8` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_8`. -/
theorem t28_8_toEdges : t28_8.toEdges = (28, [(27, 26), (26, 25), (25, 24), (24, 0), (23, 22), (22, 21), (21, 20), (20, 0), (19, 18), (18, 11), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_8` has exactly `c28_8[k]` independent sets of size `k`. -/
theorem t28_8_counts (k : Nat) : t28_8.indepCount k = c28_8.getD k 0 := by
  rw [← indepPolyRT_correct, t28_8_poly]

theorem t28_8_nlc : NLCAt t28_8.indepCount 14 := by
  unfold NLCAt; simp only [t28_8_counts]; decide

theorem t28_8_unimodal : UnimodalAt t28_8.indepCount 8 := by
  rw [funext t28_8_counts]
  exact unimodalAt_getD c28_8 8 (by decide) (by decide)

theorem t28_8_good : GoodTree t28_8 c28_8 14 8 :=
  ⟨t28_8_counts, t28_8_nlc, t28_8_unimodal⟩

/-- Witness 9 on 28 vertices (outside plain KL/KL* family), as a rose tree. -/
def t28_9 : RT := .node [.node [.node []], .node [.node [.node [.node []], .node [.node []]]], .node [.node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]]]]

/-- Census coefficient list of `t28_9`. -/
def c28_9 : List Nat := [1, 28, 351, 2615, 12950, 45119, 114011, 211907, 290076, 289114, 204105, 96791, 27776, 3752, 57, 1]

theorem t28_9_poly : indepPolyRT t28_9 = c28_9 := by decide

/-- `t28_9` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_9`. -/
theorem t28_9_toEdges : t28_9.toEdges = (28, [(27, 26), (26, 0), (25, 24), (24, 21), (23, 22), (22, 21), (21, 20), (20, 0), (19, 18), (18, 11), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_9` has exactly `c28_9[k]` independent sets of size `k`. -/
theorem t28_9_counts (k : Nat) : t28_9.indepCount k = c28_9.getD k 0 := by
  rw [← indepPolyRT_correct, t28_9_poly]

theorem t28_9_nlc : NLCAt t28_9.indepCount 14 := by
  unfold NLCAt; simp only [t28_9_counts]; decide

theorem t28_9_unimodal : UnimodalAt t28_9.indepCount 8 := by
  rw [funext t28_9_counts]
  exact unimodalAt_getD c28_9 8 (by decide) (by decide)

theorem t28_9_good : GoodTree t28_9 c28_9 14 8 :=
  ⟨t28_9_counts, t28_9_nlc, t28_9_unimodal⟩

/-- Witness 10 on 28 vertices (outside plain KL/KL* family), as a rose tree. -/
def t28_10 : RT := .node [.node [.node [.node [.node []], .node [.node []], .node [.node []]]], .node [.node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]]]]

/-- Census coefficient list of `t28_10`. -/
def c28_10 : List Nat := [1, 28, 351, 2616, 12971, 45302, 114894, 214535, 295100, 295252, 208603, 98375, 27748, 3618, 60, 1]

theorem t28_10_poly : indepPolyRT t28_10 = c28_10 := by decide

/-- `t28_10` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_10`. -/
theorem t28_10_toEdges : t28_10.toEdges = (28, [(27, 26), (26, 21), (25, 24), (24, 21), (23, 22), (22, 21), (21, 20), (20, 0), (19, 18), (18, 11), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_10` has exactly `c28_10[k]` independent sets of size `k`. -/
theorem t28_10_counts (k : Nat) : t28_10.indepCount k = c28_10.getD k 0 := by
  rw [← indepPolyRT_correct, t28_10_poly]

theorem t28_10_nlc : NLCAt t28_10.indepCount 14 := by
  unfold NLCAt; simp only [t28_10_counts]; decide

theorem t28_10_unimodal : UnimodalAt t28_10.indepCount 9 := by
  rw [funext t28_10_counts]
  exact unimodalAt_getD c28_10 9 (by decide) (by decide)

theorem t28_10_good : GoodTree t28_10 c28_10 14 9 :=
  ⟨t28_10_counts, t28_10_nlc, t28_10_unimodal⟩

/-- Witness 11 on 28 vertices (T*_{3,3,5} (KL* family)), as a rose tree. -/
def t28_11 : RT := .node [.node [.node []], .node [.node []], .node [.node [.node [.node []]]], .node [.node [.node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []], .node [.node []]]]]

/-- Census coefficient list of `t28_11`. -/
def c28_11 : List Nat := [1, 28, 351, 2617, 12987, 45423, 115475, 216493, 299860, 303540, 218649, 106408, 31558, 4436, 65, 1]

theorem t28_11_poly : indepPolyRT t28_11 = c28_11 := by decide

/-- `t28_11` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_11`. -/
theorem t28_11_toEdges : t28_11.toEdges = (28, [(27, 26), (26, 0), (25, 24), (24, 0), (23, 22), (22, 21), (21, 20), (20, 0), (19, 18), (18, 13), (17, 16), (16, 13), (15, 14), (14, 13), (13, 1), (12, 11), (11, 2), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_11` has exactly `c28_11[k]` independent sets of size `k`. -/
theorem t28_11_counts (k : Nat) : t28_11.indepCount k = c28_11.getD k 0 := by
  rw [← indepPolyRT_correct, t28_11_poly]

theorem t28_11_nlc : NLCAt t28_11.indepCount 14 := by
  unfold NLCAt; simp only [t28_11_counts]; decide

theorem t28_11_unimodal : UnimodalAt t28_11.indepCount 9 := by
  rw [funext t28_11_counts]
  exact unimodalAt_getD c28_11 9 (by decide) (by decide)

theorem t28_11_good : GoodTree t28_11 c28_11 14 9 :=
  ⟨t28_11_counts, t28_11_nlc, t28_11_unimodal⟩

/-- Witness 12 on 28 vertices (T*_{2,4,5} (KL* family)), as a rose tree. -/
def t28_12 : RT := .node [.node [.node []], .node [.node [.node [.node []]]], .node [.node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []], .node [.node []]]]]

/-- Census coefficient list of `t28_12`. -/
def c28_12 : List Nat := [1, 28, 351, 2618, 13006, 45579, 116207, 218672, 304159, 309214, 223558, 109034, 32322, 4525, 67, 1]

theorem t28_12_poly : indepPolyRT t28_12 = c28_12 := by decide

/-- `t28_12` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_12`. -/
theorem t28_12_toEdges : t28_12.toEdges = (28, [(27, 26), (26, 0), (25, 24), (24, 23), (23, 22), (22, 0), (21, 20), (20, 13), (19, 18), (18, 13), (17, 16), (16, 13), (15, 14), (14, 13), (13, 1), (12, 11), (11, 2), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_12` has exactly `c28_12[k]` independent sets of size `k`. -/
theorem t28_12_counts (k : Nat) : t28_12.indepCount k = c28_12.getD k 0 := by
  rw [← indepPolyRT_correct, t28_12_poly]

theorem t28_12_nlc : NLCAt t28_12.indepCount 14 := by
  unfold NLCAt; simp only [t28_12_counts]; decide

theorem t28_12_unimodal : UnimodalAt t28_12.indepCount 9 := by
  rw [funext t28_12_counts]
  exact unimodalAt_getD c28_12 9 (by decide) (by decide)

theorem t28_12_good : GoodTree t28_12 c28_12 14 9 :=
  ⟨t28_12_counts, t28_12_nlc, t28_12_unimodal⟩

/-- Witness 13 on 28 vertices (outside plain KL/KL* family), as a rose tree. -/
def t28_13 : RT := .node [.node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node [.node [.node []]]]], .node [.node [.node []], .node [.node []], .node [.node [.node [.node []]]]]]

/-- Census coefficient list of `t28_13`. -/
def c28_13 : List Nat := [1, 28, 351, 2613, 12910, 44774, 112316, 206639, 279233, 274137, 190411, 88881, 25180, 3383, 54, 1]

theorem t28_13_poly : indepPolyRT t28_13 = c28_13 := by decide

/-- `t28_13` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_13`. -/
theorem t28_13_toEdges : t28_13.toEdges = (28, [(27, 26), (26, 19), (25, 24), (24, 19), (23, 22), (22, 19), (21, 20), (20, 19), (19, 0), (18, 17), (17, 10), (16, 15), (15, 10), (14, 13), (13, 12), (12, 11), (11, 10), (10, 0), (9, 8), (8, 1), (7, 6), (6, 1), (5, 4), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_13` has exactly `c28_13[k]` independent sets of size `k`. -/
theorem t28_13_counts (k : Nat) : t28_13.indepCount k = c28_13.getD k 0 := by
  rw [← indepPolyRT_correct, t28_13_poly]

theorem t28_13_nlc : NLCAt t28_13.indepCount 14 := by
  unfold NLCAt; simp only [t28_13_counts]; decide

theorem t28_13_unimodal : UnimodalAt t28_13.indepCount 8 := by
  rw [funext t28_13_counts]
  exact unimodalAt_getD c28_13 8 (by decide) (by decide)

theorem t28_13_good : GoodTree t28_13 c28_13 14 8 :=
  ⟨t28_13_counts, t28_13_nlc, t28_13_unimodal⟩

/-- Witness 14 on 28 vertices (outside plain KL/KL* family), as a rose tree. -/
def t28_14 : RT := .node [.node [.node [.node []], .node [.node []], .node [.node [.node [.node []]]]], .node [.node [.node []], .node [.node []], .node [.node [.node [.node []]]]], .node [.node [.node []], .node [.node []], .node [.node [.node [.node []]]]]]

/-- Census coefficient list of `t28_14`. -/
def c28_14 : List Nat := [1, 28, 351, 2610, 12851, 44268, 109825, 198842, 263007, 251373, 169117, 76143, 20765, 2703, 51, 1]

theorem t28_14_poly : indepPolyRT t28_14 = c28_14 := by decide

/-- `t28_14` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_14`. -/
theorem t28_14_toEdges : t28_14.toEdges = (28, [(27, 26), (26, 19), (25, 24), (24, 19), (23, 22), (22, 21), (21, 20), (20, 19), (19, 0), (18, 17), (17, 10), (16, 15), (15, 10), (14, 13), (13, 12), (12, 11), (11, 10), (10, 0), (9, 8), (8, 1), (7, 6), (6, 1), (5, 4), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_14` has exactly `c28_14[k]` independent sets of size `k`. -/
theorem t28_14_counts (k : Nat) : t28_14.indepCount k = c28_14.getD k 0 := by
  rw [← indepPolyRT_correct, t28_14_poly]

theorem t28_14_nlc : NLCAt t28_14.indepCount 14 := by
  unfold NLCAt; simp only [t28_14_counts]; decide

theorem t28_14_unimodal : UnimodalAt t28_14.indepCount 8 := by
  rw [funext t28_14_counts]
  exact unimodalAt_getD c28_14 8 (by decide) (by decide)

theorem t28_14_good : GoodTree t28_14 c28_14 14 8 :=
  ⟨t28_14_counts, t28_14_nlc, t28_14_unimodal⟩

/-- Witness 15 on 28 vertices (outside plain KL/KL* family), as a rose tree. -/
def t28_15 : RT := .node [.node [.node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node [.node [.node []]]]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node [.node [.node []]]]]]

/-- Census coefficient list of `t28_15`. -/
def c28_15 : List Nat := [1, 28, 351, 2613, 12910, 44775, 112331, 206734, 279566, 274846, 191354, 89652, 25541, 3463, 58, 1]

theorem t28_15_poly : indepPolyRT t28_15 = c28_15 := by decide

/-- `t28_15` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_15`. -/
theorem t28_15_toEdges : t28_15.toEdges = (28, [(27, 26), (26, 21), (25, 24), (24, 21), (23, 22), (22, 21), (21, 0), (20, 19), (19, 12), (18, 17), (17, 12), (16, 15), (15, 14), (14, 13), (13, 12), (12, 0), (11, 10), (10, 1), (9, 8), (8, 1), (7, 6), (6, 1), (5, 4), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_15` has exactly `c28_15[k]` independent sets of size `k`. -/
theorem t28_15_counts (k : Nat) : t28_15.indepCount k = c28_15.getD k 0 := by
  rw [← indepPolyRT_correct, t28_15_poly]

theorem t28_15_nlc : NLCAt t28_15.indepCount 14 := by
  unfold NLCAt; simp only [t28_15_counts]; decide

theorem t28_15_unimodal : UnimodalAt t28_15.indepCount 8 := by
  rw [funext t28_15_counts]
  exact unimodalAt_getD c28_15 8 (by decide) (by decide)

theorem t28_15_good : GoodTree t28_15 c28_15 14 8 :=
  ⟨t28_15_counts, t28_15_nlc, t28_15_unimodal⟩

/-- Witness 16 on 28 vertices (outside plain KL/KL* family), as a rose tree. -/
def t28_16 : RT := .node [.node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node [.node [.node []]]]], .node [.node [.node [.node [.node []]]], .node [.node [.node [.node []]]]]]

/-- Census coefficient list of `t28_16`. -/
def c28_16 : List Nat := [1, 28, 351, 2611, 12870, 44423, 110536, 200859, 266672, 255641, 172209, 77447, 21051, 2732, 52, 1]

theorem t28_16_poly : indepPolyRT t28_16 = c28_16 := by decide

/-- `t28_16` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_16`. -/
theorem t28_16_toEdges : t28_16.toEdges = (28, [(27, 26), (26, 19), (25, 24), (24, 19), (23, 22), (22, 19), (21, 20), (20, 19), (19, 0), (18, 17), (17, 10), (16, 15), (15, 10), (14, 13), (13, 12), (12, 11), (11, 10), (10, 0), (9, 8), (8, 7), (7, 6), (6, 1), (5, 4), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_16` has exactly `c28_16[k]` independent sets of size `k`. -/
theorem t28_16_counts (k : Nat) : t28_16.indepCount k = c28_16.getD k 0 := by
  rw [← indepPolyRT_correct, t28_16_poly]

theorem t28_16_nlc : NLCAt t28_16.indepCount 14 := by
  unfold NLCAt; simp only [t28_16_counts]; decide

theorem t28_16_unimodal : UnimodalAt t28_16.indepCount 8 := by
  rw [funext t28_16_counts]
  exact unimodalAt_getD c28_16 8 (by decide) (by decide)

theorem t28_16_good : GoodTree t28_16 c28_16 14 8 :=
  ⟨t28_16_counts, t28_16_nlc, t28_16_unimodal⟩

/-- Witness 17 on 28 vertices (outside plain KL/KL* family), as a rose tree. -/
def t28_17 : RT := .node [.node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node [.node [.node []]]]], .node [.node [.node []], .node [.node [.node [.node []], .node [.node []]]]]]

/-- Census coefficient list of `t28_17`. -/
def c28_17 : List Nat := [1, 28, 351, 2612, 12891, 44613, 111515, 204049, 273549, 265569, 181659, 83089, 22940, 2999, 54, 1]

theorem t28_17_poly : indepPolyRT t28_17 = c28_17 := by decide

/-- `t28_17` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_17`. -/
theorem t28_17_toEdges : t28_17.toEdges = (28, [(27, 26), (26, 19), (25, 24), (24, 19), (23, 22), (22, 19), (21, 20), (20, 19), (19, 0), (18, 17), (17, 10), (16, 15), (15, 10), (14, 13), (13, 12), (12, 11), (11, 10), (10, 0), (9, 8), (8, 1), (7, 6), (6, 3), (5, 4), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_17` has exactly `c28_17[k]` independent sets of size `k`. -/
theorem t28_17_counts (k : Nat) : t28_17.indepCount k = c28_17.getD k 0 := by
  rw [← indepPolyRT_correct, t28_17_poly]

theorem t28_17_nlc : NLCAt t28_17.indepCount 14 := by
  unfold NLCAt; simp only [t28_17_counts]; decide

theorem t28_17_unimodal : UnimodalAt t28_17.indepCount 8 := by
  rw [funext t28_17_counts]
  exact unimodalAt_getD c28_17 8 (by decide) (by decide)

theorem t28_17_good : GoodTree t28_17 c28_17 14 8 :=
  ⟨t28_17_counts, t28_17_nlc, t28_17_unimodal⟩

/-- Witness 18 on 28 vertices (outside plain KL/KL* family), as a rose tree. -/
def t28_18 : RT := .node [.node [.node [.node [.node [.node []]]]], .node [.node [.node []], .node [.node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]]]]]

/-- Census coefficient list of `t28_18`. -/
def c28_18 : List Nat := [1, 28, 351, 2614, 12929, 44928, 113013, 208567, 282554, 277520, 191989, 88555, 24480, 3159, 55, 1]

theorem t28_18_poly : indepPolyRT t28_18 = c28_18 := by decide

/-- `t28_18` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_18`. -/
theorem t28_18_toEdges : t28_18.toEdges = (28, [(27, 26), (26, 25), (25, 24), (24, 23), (23, 0), (22, 21), (21, 1), (20, 19), (19, 12), (18, 17), (17, 12), (16, 15), (15, 12), (14, 13), (13, 12), (12, 2), (11, 10), (10, 3), (9, 8), (8, 3), (7, 6), (6, 3), (5, 4), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_18` has exactly `c28_18[k]` independent sets of size `k`. -/
theorem t28_18_counts (k : Nat) : t28_18.indepCount k = c28_18.getD k 0 := by
  rw [← indepPolyRT_correct, t28_18_poly]

theorem t28_18_nlc : NLCAt t28_18.indepCount 14 := by
  unfold NLCAt; simp only [t28_18_counts]; decide

theorem t28_18_unimodal : UnimodalAt t28_18.indepCount 8 := by
  rw [funext t28_18_counts]
  exact unimodalAt_getD c28_18 8 (by decide) (by decide)

theorem t28_18_good : GoodTree t28_18 c28_18 14 8 :=
  ⟨t28_18_counts, t28_18_nlc, t28_18_unimodal⟩

/-- Witness 19 on 28 vertices (outside plain KL/KL* family), as a rose tree. -/
def t28_19 : RT := .node [.node [.node [.node [.node [.node []]]]], .node [.node [.node []], .node [.node []], .node [.node [.node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]]]]]

/-- Census coefficient list of `t28_19`. -/
def c28_19 : List Nat := [1, 28, 351, 2613, 12910, 44772, 112284, 206422, 278417, 272268, 187731, 86526, 24020, 3139, 55, 1]

theorem t28_19_poly : indepPolyRT t28_19 = c28_19 := by decide

/-- `t28_19` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w28_19`. -/
theorem t28_19_toEdges : t28_19.toEdges = (28, [(27, 26), (26, 25), (25, 24), (24, 23), (23, 0), (22, 21), (21, 1), (20, 19), (19, 1), (18, 17), (17, 12), (16, 15), (15, 12), (14, 13), (13, 12), (12, 2), (11, 10), (10, 3), (9, 8), (8, 3), (7, 6), (6, 3), (5, 4), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t28_19` has exactly `c28_19[k]` independent sets of size `k`. -/
theorem t28_19_counts (k : Nat) : t28_19.indepCount k = c28_19.getD k 0 := by
  rw [← indepPolyRT_correct, t28_19_poly]

theorem t28_19_nlc : NLCAt t28_19.indepCount 14 := by
  unfold NLCAt; simp only [t28_19_counts]; decide

theorem t28_19_unimodal : UnimodalAt t28_19.indepCount 8 := by
  rw [funext t28_19_counts]
  exact unimodalAt_getD c28_19 8 (by decide) (by decide)

theorem t28_19_good : GoodTree t28_19 c28_19 14 8 :=
  ⟨t28_19_counts, t28_19_nlc, t28_19_unimodal⟩

/-- Witness 1 on 29 vertices (census), as a rose tree. -/
def t29_1 : RT := .node [.node [.node [], .node []], .node [.node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]]]

/-- Census coefficient list of `t29_1`. -/
def c29_1 : List Nat := [1, 29, 378, 2944, 15342, 56697, 153448, 309302, 466949, 525768, 435067, 257164, 103263, 25623, 3133, 54, 1]

theorem t29_1_poly : indepPolyRT t29_1 = c29_1 := by decide

/-- `t29_1` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w29_1`. -/
theorem t29_1_toEdges : t29_1.toEdges = (29, [(28, 26), (27, 26), (26, 0), (25, 24), (24, 19), (23, 22), (22, 19), (21, 20), (20, 19), (19, 0), (18, 17), (17, 10), (16, 15), (15, 10), (14, 13), (13, 10), (12, 11), (11, 10), (10, 0), (9, 8), (8, 1), (7, 6), (6, 1), (5, 4), (4, 1), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t29_1` has exactly `c29_1[k]` independent sets of size `k`. -/
theorem t29_1_counts (k : Nat) : t29_1.indepCount k = c29_1.getD k 0 := by
  rw [← indepPolyRT_correct, t29_1_poly]

theorem t29_1_nlc : NLCAt t29_1.indepCount 15 := by
  unfold NLCAt; simp only [t29_1_counts]; decide

theorem t29_1_unimodal : UnimodalAt t29_1.indepCount 9 := by
  rw [funext t29_1_counts]
  exact unimodalAt_getD c29_1 9 (by decide) (by decide)

theorem t29_1_good : GoodTree t29_1 c29_1 15 9 :=
  ⟨t29_1_counts, t29_1_nlc, t29_1_unimodal⟩

/-- Witness 2 on 29 vertices (census), as a rose tree. -/
def t29_2 : RT := .node [.node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node [], .node []]]]

/-- Census coefficient list of `t29_2`. -/
def c29_2 : List Nat := [1, 29, 378, 2945, 15368, 56971, 155051, 315195, 481361, 549708, 461867, 276546, 111402, 27072, 3090, 53, 1]

theorem t29_2_poly : indepPolyRT t29_2 = c29_2 := by decide

/-- `t29_2` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w29_2`. -/
theorem t29_2_toEdges : t29_2.toEdges = (29, [(28, 27), (27, 20), (26, 25), (25, 20), (24, 23), (23, 20), (22, 21), (21, 20), (20, 0), (19, 18), (18, 11), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 0), (10, 9), (9, 1), (8, 7), (7, 1), (6, 5), (5, 1), (4, 2), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t29_2` has exactly `c29_2[k]` independent sets of size `k`. -/
theorem t29_2_counts (k : Nat) : t29_2.indepCount k = c29_2.getD k 0 := by
  rw [← indepPolyRT_correct, t29_2_poly]

theorem t29_2_nlc : NLCAt t29_2.indepCount 15 := by
  unfold NLCAt; simp only [t29_2_counts]; decide

theorem t29_2_unimodal : UnimodalAt t29_2.indepCount 9 := by
  rw [funext t29_2_counts]
  exact unimodalAt_getD c29_2 9 (by decide) (by decide)

theorem t29_2_good : GoodTree t29_2 c29_2 15 9 :=
  ⟨t29_2_counts, t29_2_nlc, t29_2_unimodal⟩

/-- Witness 3 on 29 vertices (census), as a rose tree. -/
def t29_3 : RT := .node [.node [.node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []], .node [.node [], .node []]]]

/-- Census coefficient list of `t29_3`. -/
def c29_3 : List Nat := [1, 29, 378, 2946, 15386, 57113, 155701, 317114, 485190, 554951, 466748, 279521, 112492, 27268, 3098, 53, 1]

theorem t29_3_poly : indepPolyRT t29_3 = c29_3 := by decide

/-- `t29_3` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w29_3`. -/
theorem t29_3_toEdges : t29_3.toEdges = (29, [(28, 27), (27, 22), (26, 25), (25, 22), (24, 23), (23, 22), (22, 0), (21, 20), (20, 13), (19, 18), (18, 13), (17, 16), (16, 13), (15, 14), (14, 13), (13, 0), (12, 11), (11, 1), (10, 9), (9, 1), (8, 7), (7, 1), (6, 5), (5, 1), (4, 2), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t29_3` has exactly `c29_3[k]` independent sets of size `k`. -/
theorem t29_3_counts (k : Nat) : t29_3.indepCount k = c29_3.getD k 0 := by
  rw [← indepPolyRT_correct, t29_3_poly]

theorem t29_3_nlc : NLCAt t29_3.indepCount 15 := by
  unfold NLCAt; simp only [t29_3_counts]; decide

theorem t29_3_unimodal : UnimodalAt t29_3.indepCount 9 := by
  rw [funext t29_3_counts]
  exact unimodalAt_getD c29_3 9 (by decide) (by decide)

theorem t29_3_good : GoodTree t29_3 c29_3 15 9 :=
  ⟨t29_3_counts, t29_3_nlc, t29_3_unimodal⟩

/-- Witness 4 on 29 vertices (census), as a rose tree. -/
def t29_4 : RT := .node [.node [.node []], .node [.node []], .node [.node []], .node [.node [.node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]]], .node [.node [.node [.node [], .node []]]]]

/-- Census coefficient list of `t29_4`. -/
def c29_4 : List Nat := [1, 29, 378, 2942, 15309, 56464, 152535, 307174, 464128, 524358, 436596, 260180, 105179, 26018, 3091, 53, 1]

theorem t29_4_poly : indepPolyRT t29_4 = c29_4 := by decide

/-- `t29_4` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w29_4`. -/
theorem t29_4_toEdges : t29_4.toEdges = (29, [(28, 27), (27, 0), (26, 25), (25, 0), (24, 23), (23, 0), (22, 21), (21, 16), (20, 19), (19, 16), (18, 17), (17, 16), (16, 6), (15, 14), (14, 7), (13, 12), (12, 7), (11, 10), (10, 7), (9, 8), (8, 7), (7, 6), (6, 0), (5, 3), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t29_4` has exactly `c29_4[k]` independent sets of size `k`. -/
theorem t29_4_counts (k : Nat) : t29_4.indepCount k = c29_4.getD k 0 := by
  rw [← indepPolyRT_correct, t29_4_poly]

theorem t29_4_nlc : NLCAt t29_4.indepCount 15 := by
  unfold NLCAt; simp only [t29_4_counts]; decide

theorem t29_4_unimodal : UnimodalAt t29_4.indepCount 9 := by
  rw [funext t29_4_counts]
  exact unimodalAt_getD c29_4 9 (by decide) (by decide)

theorem t29_4_good : GoodTree t29_4 c29_4 15 9 :=
  ⟨t29_4_counts, t29_4_nlc, t29_4_unimodal⟩

/-- Witness 5 on 29 vertices (census), as a rose tree. -/
def t29_5 : RT := .node [.node [.node []], .node [.node []], .node [.node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]]], .node [.node [.node [.node [], .node []]]]]

/-- Census coefficient list of `t29_5`. -/
def c29_5 : List Nat := [1, 29, 378, 2942, 15309, 56463, 152520, 307079, 463793, 523634, 435609, 259346, 104774, 25926, 3087, 53, 1]

theorem t29_5_poly : indepPolyRT t29_5 = c29_5 := by decide

/-- `t29_5` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w29_5`. -/
theorem t29_5_toEdges : t29_5.toEdges = (29, [(28, 27), (27, 0), (26, 25), (25, 0), (24, 23), (23, 16), (22, 21), (21, 16), (20, 19), (19, 16), (18, 17), (17, 16), (16, 6), (15, 14), (14, 7), (13, 12), (12, 7), (11, 10), (10, 7), (9, 8), (8, 7), (7, 6), (6, 0), (5, 3), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t29_5` has exactly `c29_5[k]` independent sets of size `k`. -/
theorem t29_5_counts (k : Nat) : t29_5.indepCount k = c29_5.getD k 0 := by
  rw [← indepPolyRT_correct, t29_5_poly]

theorem t29_5_nlc : NLCAt t29_5.indepCount 15 := by
  unfold NLCAt; simp only [t29_5_counts]; decide

theorem t29_5_unimodal : UnimodalAt t29_5.indepCount 9 := by
  rw [funext t29_5_counts]
  exact unimodalAt_getD c29_5 9 (by decide) (by decide)

theorem t29_5_good : GoodTree t29_5 c29_5 15 9 :=
  ⟨t29_5_counts, t29_5_nlc, t29_5_unimodal⟩

/-- Witness 6 on 29 vertices (census), as a rose tree. -/
def t29_6 : RT := .node [.node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node [], .node [.node [], .node []]]]]

/-- Census coefficient list of `t29_6`. -/
def c29_6 : List Nat := [1, 29, 378, 2943, 15329, 56637, 153392, 309884, 469879, 532704, 444839, 265556, 107342, 26483, 3129, 54, 1]

theorem t29_6_poly : indepPolyRT t29_6 = c29_6 := by decide

/-- `t29_6` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w29_6`. -/
theorem t29_6_toEdges : t29_6.toEdges = (29, [(28, 27), (27, 20), (26, 25), (25, 20), (24, 23), (23, 20), (22, 21), (21, 20), (20, 0), (19, 18), (18, 11), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 0), (10, 9), (9, 1), (8, 7), (7, 1), (6, 2), (5, 3), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t29_6` has exactly `c29_6[k]` independent sets of size `k`. -/
theorem t29_6_counts (k : Nat) : t29_6.indepCount k = c29_6.getD k 0 := by
  rw [← indepPolyRT_correct, t29_6_poly]

theorem t29_6_nlc : NLCAt t29_6.indepCount 15 := by
  unfold NLCAt; simp only [t29_6_counts]; decide

theorem t29_6_unimodal : UnimodalAt t29_6.indepCount 9 := by
  rw [funext t29_6_counts]
  exact unimodalAt_getD c29_6 9 (by decide) (by decide)

theorem t29_6_good : GoodTree t29_6 c29_6 15 9 :=
  ⟨t29_6_counts, t29_6_nlc, t29_6_unimodal⟩

/-- Witness 7 on 29 vertices (census), as a rose tree. -/
def t29_7 : RT := .node [.node [.node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node []]], .node [.node [.node []], .node [.node []], .node [.node []], .node [.node [], .node [.node [], .node []]]]]

/-- Census coefficient list of `t29_7`. -/
def c29_7 : List Nat := [1, 29, 378, 2943, 15328, 56621, 153282, 309454, 468820, 530993, 443018, 264317, 106845, 26387, 3125, 54, 1]

theorem t29_7_poly : indepPolyRT t29_7 = c29_7 := by decide

/-- `t29_7` flattens to exactly the (child, parent) edge list certified in the
core (mathlib-free) package `lean/Erdosattack/Witnesses.lean` as `w29_7`. -/
theorem t29_7_toEdges : t29_7.toEdges = (29, [(28, 27), (27, 22), (26, 25), (25, 22), (24, 23), (23, 22), (22, 0), (21, 20), (20, 13), (19, 18), (18, 13), (17, 16), (16, 13), (15, 14), (14, 13), (13, 0), (12, 11), (11, 1), (10, 9), (9, 1), (8, 7), (7, 1), (6, 2), (5, 3), (4, 3), (3, 2), (2, 1), (1, 0)]) := by decide

/-- Semantic count: `t29_7` has exactly `c29_7[k]` independent sets of size `k`. -/
theorem t29_7_counts (k : Nat) : t29_7.indepCount k = c29_7.getD k 0 := by
  rw [← indepPolyRT_correct, t29_7_poly]

theorem t29_7_nlc : NLCAt t29_7.indepCount 15 := by
  unfold NLCAt; simp only [t29_7_counts]; decide

theorem t29_7_unimodal : UnimodalAt t29_7.indepCount 9 := by
  rw [funext t29_7_counts]
  exact unimodalAt_getD c29_7 9 (by decide) (by decide)

theorem t29_7_good : GoodTree t29_7 c29_7 15 9 :=
  ⟨t29_7_counts, t29_7_nlc, t29_7_unimodal⟩

/-- **Headline (n = 26).** Each of the 2 census trees on 26 vertices has
independence-set counts given exactly by its census coefficient list, and that
counting sequence `k ↦ #{independent S ⊆ V, |S| = k}` breaks log-concavity
yet is unimodal. -/
theorem headline_n26 :
    GoodTree t26_1 c26_1 13 8 ∧
    GoodTree t26_2 c26_2 13 8 :=
  ⟨t26_1_good, t26_2_good⟩

/-- **Headline (n = 28).** Each of the 19 census trees on 28 vertices has
independence-set counts given exactly by its census coefficient list, and that
counting sequence `k ↦ #{independent S ⊆ V, |S| = k}` breaks log-concavity
yet is unimodal. -/
theorem headline_n28 :
    GoodTree t28_1 c28_1 14 9 ∧
    GoodTree t28_2 c28_2 14 9 ∧
    GoodTree t28_3 c28_3 14 9 ∧
    GoodTree t28_4 c28_4 14 9 ∧
    GoodTree t28_5 c28_5 14 8 ∧
    GoodTree t28_6 c28_6 14 8 ∧
    GoodTree t28_7 c28_7 14 9 ∧
    GoodTree t28_8 c28_8 14 8 ∧
    GoodTree t28_9 c28_9 14 8 ∧
    GoodTree t28_10 c28_10 14 9 ∧
    GoodTree t28_11 c28_11 14 9 ∧
    GoodTree t28_12 c28_12 14 9 ∧
    GoodTree t28_13 c28_13 14 8 ∧
    GoodTree t28_14 c28_14 14 8 ∧
    GoodTree t28_15 c28_15 14 8 ∧
    GoodTree t28_16 c28_16 14 8 ∧
    GoodTree t28_17 c28_17 14 8 ∧
    GoodTree t28_18 c28_18 14 8 ∧
    GoodTree t28_19 c28_19 14 8 :=
  ⟨t28_1_good, t28_2_good, t28_3_good, t28_4_good, t28_5_good, t28_6_good, t28_7_good, t28_8_good, t28_9_good, t28_10_good, t28_11_good, t28_12_good, t28_13_good, t28_14_good, t28_15_good, t28_16_good, t28_17_good, t28_18_good, t28_19_good⟩

/-- **Headline (n = 29).** Each of the 7 census trees on 29 vertices has
independence-set counts given exactly by its census coefficient list, and that
counting sequence `k ↦ #{independent S ⊆ V, |S| = k}` breaks log-concavity
yet is unimodal. -/
theorem headline_n29 :
    GoodTree t29_1 c29_1 15 9 ∧
    GoodTree t29_2 c29_2 15 9 ∧
    GoodTree t29_3 c29_3 15 9 ∧
    GoodTree t29_4 c29_4 15 9 ∧
    GoodTree t29_5 c29_5 15 9 ∧
    GoodTree t29_6 c29_6 15 9 ∧
    GoodTree t29_7 c29_7 15 9 :=
  ⟨t29_1_good, t29_2_good, t29_3_good, t29_4_good, t29_5_good, t29_6_good, t29_7_good⟩

end ErdosattackM
