#!/usr/bin/env python3
"""Generate Erdosattack/Witnesses.lean from the NLC census JSONs.

Each witness tree (1-indexed parent array, root 1 with parent 0) becomes a
0-indexed (child, parent) edge list in decreasing child order, which satisfies
the children-before-parents processing requirement since parent[i] < i.
Sanity-checks the DP in Python against the census coefficients first.
"""
import json
from pathlib import Path

HERE = Path(__file__).parent
CENSUS = [HERE.parent / "p993" / f"nlc_n{n}_census.json" for n in (26, 28, 29)]


def add(p, q):
    out = [0] * max(len(p), len(q))
    for i, c in enumerate(p):
        out[i] += c
    for i, c in enumerate(q):
        out[i] += c
    return out


def mul(p, q):
    out = [0] * (len(p) + len(q) - 1) if p and q else []
    for i, a in enumerate(p):
        for j, b in enumerate(q):
            out[i + j] += a * b
    return out


def indep_poly(n, edges):
    st = [([0, 1], [1]) for _ in range(n)]
    for c, p in edges:
        ac, bc = st[c]
        ap, bp = st[p]
        st[p] = (mul(ap, bc), mul(bp, add(ac, bc)))
    a0, b0 = st[0]
    return add(a0, b0)


defs, names = [], []
for path in CENSUS:
    d = json.loads(path.read_text())
    for idx, t in enumerate(d["trees"], 1):
        n = t["n"]
        par = t["parent_array_1indexed"]
        assert par[0] == 0 and all(par[i] - 1 < i for i in range(1, n)), "need parent[i] < i"
        edges = [(i, par[i] - 1) for i in range(n - 1, 0, -1)]
        got = indep_poly(n, edges)
        assert got == t["coefficients"], (path.name, idx)
        name = f"w{n}_{idx}"
        names.append((name, n))
        coeffs = ", ".join(map(str, t["coefficients"]))
        es = ", ".join(f"({c}, {p})" for c, p in edges)
        defs.append(f"""/-- Witness {idx} on {n} vertices ({t.get('family_id', 'census')}). -/
def {name} : List (Nat × Nat) := [{es}]

theorem {name}_poly : indepPoly {n} {name} = [{coeffs}] := by decide

theorem {name}_not_logConcave : hasLCFailure (indepPoly {n} {name}) = true := by decide

theorem {name}_unimodal : isUnimodal (indepPoly {n} {name}) = true := by decide
""")

all_list = ", ".join(f"({n}, {name})" for name, n in names)
out = f"""import Erdosattack.IndepPoly
/-!
# The 28 known minimal-order non-log-concave trees, kernel-certified

Generated by `gen_witnesses.py` from the census files in `../p993/`
(2 trees on 26 vertices, 19 on 28, 7 on 29 — the n = 29 census first
computed 2026-07-24). Every theorem is closed by `decide`: the Lean kernel
recomputes each independence polynomial and checks the log-concavity failure
and unimodality. No axioms are used (verify with `#print axioms`).
-/

namespace Erdosattack

{chr(10).join(defs)}
/-- All 28 witnesses, as `(n, edges)` pairs. -/
def allWitnesses : List (Nat × List (Nat × Nat)) := [{all_list}]

/-- Every census witness has a non-log-concave yet unimodal
independence polynomial. -/
theorem all_witnesses_nlc_unimodal :
    allWitnesses.all (fun t =>
      hasLCFailure (indepPoly t.1 t.2) && isUnimodal (indepPoly t.1 t.2)) = true := by
  decide

end Erdosattack
"""
(HERE / "Erdosattack" / "Witnesses.lean").write_text(out)
print(f"wrote Witnesses.lean: {len(names)} witnesses")
