import Erdosattack.IndepPoly
/-!
# The 28 known minimal-order non-log-concave trees, kernel-certified

Generated by `gen_witnesses.py` from the census files in `../p993/`
(2 trees on 26 vertices, 19 on 28, 7 on 29 — the n = 29 census first
computed 2026-07-24). Every theorem is closed by `decide`: the Lean kernel
recomputes each independence polynomial and checks the log-concavity failure
and unimodality. No axioms are used (verify with `#print axioms`).
-/

namespace Erdosattack

/-- Witness 1 on 26 vertices (T_{3,4,4} (Kadrawi-Levit)). -/
def w26_1 : List (Nat × Nat) := [(25, 24), (24, 19), (23, 22), (22, 19), (21, 20), (20, 19), (19, 0), (18, 17), (17, 10), (16, 15), (15, 10), (14, 13), (13, 10), (12, 11), (11, 10), (10, 0), (9, 8), (8, 1), (7, 6), (6, 1), (5, 4), (4, 1), (3, 2), (2, 1), (1, 0)]

theorem w26_1_poly : indepPoly 26 w26_1 = [1, 26, 300, 2040, 9142, 28551, 63933, 103736, 121376, 100144, 55499, 18683, 2979, 51, 1] := by decide

theorem w26_1_not_logConcave : hasLCFailure (indepPoly 26 w26_1) = true := by decide

theorem w26_1_unimodal : isUnimodal (indepPoly 26 w26_1) = true := by decide

/-- Witness 2 on 26 vertices (T*_{3,3,4} (Kadrawi-Levit)). -/
def w26_2 : List (Nat × Nat) := [(25, 24), (24, 0), (23, 22), (22, 0), (21, 20), (20, 19), (19, 18), (18, 0), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w26_2_poly : indepPoly 26 w26_2 = [1, 26, 300, 2037, 9089, 28147, 62183, 98968, 112870, 90178, 48086, 15498, 2372, 48, 1] := by decide

theorem w26_2_not_logConcave : hasLCFailure (indepPoly 26 w26_2) = true := by decide

theorem w26_2_unimodal : isUnimodal (indepPoly 26 w26_2) = true := by decide

/-- Witness 1 on 28 vertices (T_{4,4,4} (KL family)). -/
def w28_1 : List (Nat × Nat) := [(27, 26), (26, 19), (25, 24), (24, 19), (23, 22), (22, 19), (21, 20), (20, 19), (19, 0), (18, 17), (17, 10), (16, 15), (15, 10), (14, 13), (13, 10), (12, 11), (11, 10), (10, 0), (9, 8), (8, 1), (7, 6), (6, 1), (5, 4), (4, 1), (3, 2), (2, 1), (1, 0)]

theorem w28_1_poly : indepPoly 28 w28_1 = [1, 28, 351, 2619, 13028, 45789, 117358, 222711, 313692, 324596, 240347, 120903, 37220, 5410, 60, 1] := by decide

theorem w28_1_not_logConcave : hasLCFailure (indepPoly 28 w28_1) = true := by decide

theorem w28_1_unimodal : isUnimodal (indepPoly 28 w28_1) = true := by decide

/-- Witness 2 on 28 vertices (T_{3,4,5} (KL family)). -/
def w28_2 : List (Nat × Nat) := [(27, 26), (26, 21), (25, 24), (24, 21), (23, 22), (22, 21), (21, 0), (20, 19), (19, 12), (18, 17), (17, 12), (16, 15), (15, 12), (14, 13), (13, 12), (12, 0), (11, 10), (10, 1), (9, 8), (8, 1), (7, 6), (6, 1), (5, 4), (4, 1), (3, 2), (2, 1), (1, 0)]

theorem w28_2_poly : indepPoly 28 w28_2 = [1, 28, 351, 2620, 13046, 45931, 118008, 224630, 317521, 329839, 245228, 123878, 38310, 5606, 68, 1] := by decide

theorem w28_2_not_logConcave : hasLCFailure (indepPoly 28 w28_2) = true := by decide

theorem w28_2_unimodal : isUnimodal (indepPoly 28 w28_2) = true := by decide

/-- Witness 3 on 28 vertices (outside plain KL/KL* family). -/
def w28_3 : List (Nat × Nat) := [(27, 26), (26, 0), (25, 24), (24, 0), (23, 22), (22, 0), (21, 18), (20, 19), (19, 18), (18, 0), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_3_poly : indepPoly 28 w28_3 = [1, 28, 351, 2617, 12988, 45439, 115589, 216970, 301151, 305881, 221498, 108674, 32663, 4725, 95, 2] := by decide

theorem w28_3_not_logConcave : hasLCFailure (indepPoly 28 w28_3) = true := by decide

theorem w28_3_unimodal : isUnimodal (indepPoly 28 w28_3) = true := by decide

/-- Witness 4 on 28 vertices (outside plain KL/KL* family). -/
def w28_4 : List (Nat × Nat) := [(27, 26), (26, 0), (25, 24), (24, 0), (23, 22), (22, 0), (21, 20), (20, 19), (19, 18), (18, 0), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_4_poly : indepPoly 28 w28_4 = [1, 28, 351, 2616, 12969, 45282, 114842, 214690, 296459, 299246, 215076, 104537, 30997, 4356, 61, 1] := by decide

theorem w28_4_not_logConcave : hasLCFailure (indepPoly 28 w28_4) = true := by decide

theorem w28_4_unimodal : isUnimodal (indepPoly 28 w28_4) = true := by decide

/-- Witness 5 on 28 vertices (outside plain KL/KL* family). -/
def w28_5 : List (Nat × Nat) := [(27, 26), (26, 0), (25, 24), (24, 23), (23, 22), (22, 0), (21, 20), (20, 19), (19, 18), (18, 0), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_5_poly : indepPoly 28 w28_5 = [1, 28, 351, 2613, 12910, 44774, 112316, 206640, 279245, 274194, 190551, 89071, 25317, 3426, 56, 1] := by decide

theorem w28_5_not_logConcave : hasLCFailure (indepPoly 28 w28_5) = true := by decide

theorem w28_5_unimodal : isUnimodal (indepPoly 28 w28_5) = true := by decide

/-- Witness 6 on 28 vertices (outside plain KL/KL* family). -/
def w28_6 : List (Nat × Nat) := [(27, 26), (26, 0), (25, 24), (24, 0), (23, 22), (22, 19), (21, 20), (20, 19), (19, 18), (18, 0), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_6_poly : indepPoly 28 w28_6 = [1, 28, 351, 2614, 12931, 44964, 113296, 209844, 286205, 284389, 200504, 95269, 27541, 3779, 59, 1] := by decide

theorem w28_6_not_logConcave : hasLCFailure (indepPoly 28 w28_6) = true := by decide

theorem w28_6_unimodal : isUnimodal (indepPoly 28 w28_6) = true := by decide

/-- Witness 7 on 28 vertices (T*_{3,4,4} (KL* family)). -/
def w28_7 : List (Nat × Nat) := [(27, 26), (26, 0), (25, 24), (24, 0), (23, 22), (22, 21), (21, 20), (20, 0), (19, 18), (18, 11), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_7_poly : indepPoly 28 w28_7 = [1, 28, 351, 2616, 12969, 45281, 114827, 214595, 296124, 298522, 214089, 103703, 30592, 4264, 57, 1] := by decide

theorem w28_7_not_logConcave : hasLCFailure (indepPoly 28 w28_7) = true := by decide

theorem w28_7_unimodal : isUnimodal (indepPoly 28 w28_7) = true := by decide

/-- Witness 8 on 28 vertices (outside plain KL/KL* family). -/
def w28_8 : List (Nat × Nat) := [(27, 26), (26, 25), (25, 24), (24, 0), (23, 22), (22, 21), (21, 20), (20, 0), (19, 18), (18, 11), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_8_poly : indepPoly 28 w28_8 = [1, 28, 351, 2614, 12929, 44929, 113029, 208679, 283002, 278640, 193781, 90347, 25504, 3415, 55, 1] := by decide

theorem w28_8_not_logConcave : hasLCFailure (indepPoly 28 w28_8) = true := by decide

theorem w28_8_unimodal : isUnimodal (indepPoly 28 w28_8) = true := by decide

/-- Witness 9 on 28 vertices (outside plain KL/KL* family). -/
def w28_9 : List (Nat × Nat) := [(27, 26), (26, 0), (25, 24), (24, 21), (23, 22), (22, 21), (21, 20), (20, 0), (19, 18), (18, 11), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_9_poly : indepPoly 28 w28_9 = [1, 28, 351, 2615, 12950, 45119, 114011, 211907, 290076, 289114, 204105, 96791, 27776, 3752, 57, 1] := by decide

theorem w28_9_not_logConcave : hasLCFailure (indepPoly 28 w28_9) = true := by decide

theorem w28_9_unimodal : isUnimodal (indepPoly 28 w28_9) = true := by decide

/-- Witness 10 on 28 vertices (outside plain KL/KL* family). -/
def w28_10 : List (Nat × Nat) := [(27, 26), (26, 21), (25, 24), (24, 21), (23, 22), (22, 21), (21, 20), (20, 0), (19, 18), (18, 11), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 1), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_10_poly : indepPoly 28 w28_10 = [1, 28, 351, 2616, 12971, 45302, 114894, 214535, 295100, 295252, 208603, 98375, 27748, 3618, 60, 1] := by decide

theorem w28_10_not_logConcave : hasLCFailure (indepPoly 28 w28_10) = true := by decide

theorem w28_10_unimodal : isUnimodal (indepPoly 28 w28_10) = true := by decide

/-- Witness 11 on 28 vertices (T*_{3,3,5} (KL* family)). -/
def w28_11 : List (Nat × Nat) := [(27, 26), (26, 0), (25, 24), (24, 0), (23, 22), (22, 21), (21, 20), (20, 0), (19, 18), (18, 13), (17, 16), (16, 13), (15, 14), (14, 13), (13, 1), (12, 11), (11, 2), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_11_poly : indepPoly 28 w28_11 = [1, 28, 351, 2617, 12987, 45423, 115475, 216493, 299860, 303540, 218649, 106408, 31558, 4436, 65, 1] := by decide

theorem w28_11_not_logConcave : hasLCFailure (indepPoly 28 w28_11) = true := by decide

theorem w28_11_unimodal : isUnimodal (indepPoly 28 w28_11) = true := by decide

/-- Witness 12 on 28 vertices (T*_{2,4,5} (KL* family)). -/
def w28_12 : List (Nat × Nat) := [(27, 26), (26, 0), (25, 24), (24, 23), (23, 22), (22, 0), (21, 20), (20, 13), (19, 18), (18, 13), (17, 16), (16, 13), (15, 14), (14, 13), (13, 1), (12, 11), (11, 2), (10, 9), (9, 2), (8, 7), (7, 2), (6, 5), (5, 2), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_12_poly : indepPoly 28 w28_12 = [1, 28, 351, 2618, 13006, 45579, 116207, 218672, 304159, 309214, 223558, 109034, 32322, 4525, 67, 1] := by decide

theorem w28_12_not_logConcave : hasLCFailure (indepPoly 28 w28_12) = true := by decide

theorem w28_12_unimodal : isUnimodal (indepPoly 28 w28_12) = true := by decide

/-- Witness 13 on 28 vertices (outside plain KL/KL* family). -/
def w28_13 : List (Nat × Nat) := [(27, 26), (26, 19), (25, 24), (24, 19), (23, 22), (22, 19), (21, 20), (20, 19), (19, 0), (18, 17), (17, 10), (16, 15), (15, 10), (14, 13), (13, 12), (12, 11), (11, 10), (10, 0), (9, 8), (8, 1), (7, 6), (6, 1), (5, 4), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_13_poly : indepPoly 28 w28_13 = [1, 28, 351, 2613, 12910, 44774, 112316, 206639, 279233, 274137, 190411, 88881, 25180, 3383, 54, 1] := by decide

theorem w28_13_not_logConcave : hasLCFailure (indepPoly 28 w28_13) = true := by decide

theorem w28_13_unimodal : isUnimodal (indepPoly 28 w28_13) = true := by decide

/-- Witness 14 on 28 vertices (outside plain KL/KL* family). -/
def w28_14 : List (Nat × Nat) := [(27, 26), (26, 19), (25, 24), (24, 19), (23, 22), (22, 21), (21, 20), (20, 19), (19, 0), (18, 17), (17, 10), (16, 15), (15, 10), (14, 13), (13, 12), (12, 11), (11, 10), (10, 0), (9, 8), (8, 1), (7, 6), (6, 1), (5, 4), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_14_poly : indepPoly 28 w28_14 = [1, 28, 351, 2610, 12851, 44268, 109825, 198842, 263007, 251373, 169117, 76143, 20765, 2703, 51, 1] := by decide

theorem w28_14_not_logConcave : hasLCFailure (indepPoly 28 w28_14) = true := by decide

theorem w28_14_unimodal : isUnimodal (indepPoly 28 w28_14) = true := by decide

/-- Witness 15 on 28 vertices (outside plain KL/KL* family). -/
def w28_15 : List (Nat × Nat) := [(27, 26), (26, 21), (25, 24), (24, 21), (23, 22), (22, 21), (21, 0), (20, 19), (19, 12), (18, 17), (17, 12), (16, 15), (15, 14), (14, 13), (13, 12), (12, 0), (11, 10), (10, 1), (9, 8), (8, 1), (7, 6), (6, 1), (5, 4), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_15_poly : indepPoly 28 w28_15 = [1, 28, 351, 2613, 12910, 44775, 112331, 206734, 279566, 274846, 191354, 89652, 25541, 3463, 58, 1] := by decide

theorem w28_15_not_logConcave : hasLCFailure (indepPoly 28 w28_15) = true := by decide

theorem w28_15_unimodal : isUnimodal (indepPoly 28 w28_15) = true := by decide

/-- Witness 16 on 28 vertices (outside plain KL/KL* family). -/
def w28_16 : List (Nat × Nat) := [(27, 26), (26, 19), (25, 24), (24, 19), (23, 22), (22, 19), (21, 20), (20, 19), (19, 0), (18, 17), (17, 10), (16, 15), (15, 10), (14, 13), (13, 12), (12, 11), (11, 10), (10, 0), (9, 8), (8, 7), (7, 6), (6, 1), (5, 4), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_16_poly : indepPoly 28 w28_16 = [1, 28, 351, 2611, 12870, 44423, 110536, 200859, 266672, 255641, 172209, 77447, 21051, 2732, 52, 1] := by decide

theorem w28_16_not_logConcave : hasLCFailure (indepPoly 28 w28_16) = true := by decide

theorem w28_16_unimodal : isUnimodal (indepPoly 28 w28_16) = true := by decide

/-- Witness 17 on 28 vertices (outside plain KL/KL* family). -/
def w28_17 : List (Nat × Nat) := [(27, 26), (26, 19), (25, 24), (24, 19), (23, 22), (22, 19), (21, 20), (20, 19), (19, 0), (18, 17), (17, 10), (16, 15), (15, 10), (14, 13), (13, 12), (12, 11), (11, 10), (10, 0), (9, 8), (8, 1), (7, 6), (6, 3), (5, 4), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_17_poly : indepPoly 28 w28_17 = [1, 28, 351, 2612, 12891, 44613, 111515, 204049, 273549, 265569, 181659, 83089, 22940, 2999, 54, 1] := by decide

theorem w28_17_not_logConcave : hasLCFailure (indepPoly 28 w28_17) = true := by decide

theorem w28_17_unimodal : isUnimodal (indepPoly 28 w28_17) = true := by decide

/-- Witness 18 on 28 vertices (outside plain KL/KL* family). -/
def w28_18 : List (Nat × Nat) := [(27, 26), (26, 25), (25, 24), (24, 23), (23, 0), (22, 21), (21, 1), (20, 19), (19, 12), (18, 17), (17, 12), (16, 15), (15, 12), (14, 13), (13, 12), (12, 2), (11, 10), (10, 3), (9, 8), (8, 3), (7, 6), (6, 3), (5, 4), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_18_poly : indepPoly 28 w28_18 = [1, 28, 351, 2614, 12929, 44928, 113013, 208567, 282554, 277520, 191989, 88555, 24480, 3159, 55, 1] := by decide

theorem w28_18_not_logConcave : hasLCFailure (indepPoly 28 w28_18) = true := by decide

theorem w28_18_unimodal : isUnimodal (indepPoly 28 w28_18) = true := by decide

/-- Witness 19 on 28 vertices (outside plain KL/KL* family). -/
def w28_19 : List (Nat × Nat) := [(27, 26), (26, 25), (25, 24), (24, 23), (23, 0), (22, 21), (21, 1), (20, 19), (19, 1), (18, 17), (17, 12), (16, 15), (15, 12), (14, 13), (13, 12), (12, 2), (11, 10), (10, 3), (9, 8), (8, 3), (7, 6), (6, 3), (5, 4), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w28_19_poly : indepPoly 28 w28_19 = [1, 28, 351, 2613, 12910, 44772, 112284, 206422, 278417, 272268, 187731, 86526, 24020, 3139, 55, 1] := by decide

theorem w28_19_not_logConcave : hasLCFailure (indepPoly 28 w28_19) = true := by decide

theorem w28_19_unimodal : isUnimodal (indepPoly 28 w28_19) = true := by decide

/-- Witness 1 on 29 vertices (census). -/
def w29_1 : List (Nat × Nat) := [(28, 26), (27, 26), (26, 0), (25, 24), (24, 19), (23, 22), (22, 19), (21, 20), (20, 19), (19, 0), (18, 17), (17, 10), (16, 15), (15, 10), (14, 13), (13, 10), (12, 11), (11, 10), (10, 0), (9, 8), (8, 1), (7, 6), (6, 1), (5, 4), (4, 1), (3, 2), (2, 1), (1, 0)]

theorem w29_1_poly : indepPoly 29 w29_1 = [1, 29, 378, 2944, 15342, 56697, 153448, 309302, 466949, 525768, 435067, 257164, 103263, 25623, 3133, 54, 1] := by decide

theorem w29_1_not_logConcave : hasLCFailure (indepPoly 29 w29_1) = true := by decide

theorem w29_1_unimodal : isUnimodal (indepPoly 29 w29_1) = true := by decide

/-- Witness 2 on 29 vertices (census). -/
def w29_2 : List (Nat × Nat) := [(28, 27), (27, 20), (26, 25), (25, 20), (24, 23), (23, 20), (22, 21), (21, 20), (20, 0), (19, 18), (18, 11), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 0), (10, 9), (9, 1), (8, 7), (7, 1), (6, 5), (5, 1), (4, 2), (3, 2), (2, 1), (1, 0)]

theorem w29_2_poly : indepPoly 29 w29_2 = [1, 29, 378, 2945, 15368, 56971, 155051, 315195, 481361, 549708, 461867, 276546, 111402, 27072, 3090, 53, 1] := by decide

theorem w29_2_not_logConcave : hasLCFailure (indepPoly 29 w29_2) = true := by decide

theorem w29_2_unimodal : isUnimodal (indepPoly 29 w29_2) = true := by decide

/-- Witness 3 on 29 vertices (census). -/
def w29_3 : List (Nat × Nat) := [(28, 27), (27, 22), (26, 25), (25, 22), (24, 23), (23, 22), (22, 0), (21, 20), (20, 13), (19, 18), (18, 13), (17, 16), (16, 13), (15, 14), (14, 13), (13, 0), (12, 11), (11, 1), (10, 9), (9, 1), (8, 7), (7, 1), (6, 5), (5, 1), (4, 2), (3, 2), (2, 1), (1, 0)]

theorem w29_3_poly : indepPoly 29 w29_3 = [1, 29, 378, 2946, 15386, 57113, 155701, 317114, 485190, 554951, 466748, 279521, 112492, 27268, 3098, 53, 1] := by decide

theorem w29_3_not_logConcave : hasLCFailure (indepPoly 29 w29_3) = true := by decide

theorem w29_3_unimodal : isUnimodal (indepPoly 29 w29_3) = true := by decide

/-- Witness 4 on 29 vertices (census). -/
def w29_4 : List (Nat × Nat) := [(28, 27), (27, 0), (26, 25), (25, 0), (24, 23), (23, 0), (22, 21), (21, 16), (20, 19), (19, 16), (18, 17), (17, 16), (16, 6), (15, 14), (14, 7), (13, 12), (12, 7), (11, 10), (10, 7), (9, 8), (8, 7), (7, 6), (6, 0), (5, 3), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w29_4_poly : indepPoly 29 w29_4 = [1, 29, 378, 2942, 15309, 56464, 152535, 307174, 464128, 524358, 436596, 260180, 105179, 26018, 3091, 53, 1] := by decide

theorem w29_4_not_logConcave : hasLCFailure (indepPoly 29 w29_4) = true := by decide

theorem w29_4_unimodal : isUnimodal (indepPoly 29 w29_4) = true := by decide

/-- Witness 5 on 29 vertices (census). -/
def w29_5 : List (Nat × Nat) := [(28, 27), (27, 0), (26, 25), (25, 0), (24, 23), (23, 16), (22, 21), (21, 16), (20, 19), (19, 16), (18, 17), (17, 16), (16, 6), (15, 14), (14, 7), (13, 12), (12, 7), (11, 10), (10, 7), (9, 8), (8, 7), (7, 6), (6, 0), (5, 3), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w29_5_poly : indepPoly 29 w29_5 = [1, 29, 378, 2942, 15309, 56463, 152520, 307079, 463793, 523634, 435609, 259346, 104774, 25926, 3087, 53, 1] := by decide

theorem w29_5_not_logConcave : hasLCFailure (indepPoly 29 w29_5) = true := by decide

theorem w29_5_unimodal : isUnimodal (indepPoly 29 w29_5) = true := by decide

/-- Witness 6 on 29 vertices (census). -/
def w29_6 : List (Nat × Nat) := [(28, 27), (27, 20), (26, 25), (25, 20), (24, 23), (23, 20), (22, 21), (21, 20), (20, 0), (19, 18), (18, 11), (17, 16), (16, 11), (15, 14), (14, 11), (13, 12), (12, 11), (11, 0), (10, 9), (9, 1), (8, 7), (7, 1), (6, 2), (5, 3), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w29_6_poly : indepPoly 29 w29_6 = [1, 29, 378, 2943, 15329, 56637, 153392, 309884, 469879, 532704, 444839, 265556, 107342, 26483, 3129, 54, 1] := by decide

theorem w29_6_not_logConcave : hasLCFailure (indepPoly 29 w29_6) = true := by decide

theorem w29_6_unimodal : isUnimodal (indepPoly 29 w29_6) = true := by decide

/-- Witness 7 on 29 vertices (census). -/
def w29_7 : List (Nat × Nat) := [(28, 27), (27, 22), (26, 25), (25, 22), (24, 23), (23, 22), (22, 0), (21, 20), (20, 13), (19, 18), (18, 13), (17, 16), (16, 13), (15, 14), (14, 13), (13, 0), (12, 11), (11, 1), (10, 9), (9, 1), (8, 7), (7, 1), (6, 2), (5, 3), (4, 3), (3, 2), (2, 1), (1, 0)]

theorem w29_7_poly : indepPoly 29 w29_7 = [1, 29, 378, 2943, 15328, 56621, 153282, 309454, 468820, 530993, 443018, 264317, 106845, 26387, 3125, 54, 1] := by decide

theorem w29_7_not_logConcave : hasLCFailure (indepPoly 29 w29_7) = true := by decide

theorem w29_7_unimodal : isUnimodal (indepPoly 29 w29_7) = true := by decide

/-- All 28 witnesses, as `(n, edges)` pairs. -/
def allWitnesses : List (Nat × List (Nat × Nat)) := [(26, w26_1), (26, w26_2), (28, w28_1), (28, w28_2), (28, w28_3), (28, w28_4), (28, w28_5), (28, w28_6), (28, w28_7), (28, w28_8), (28, w28_9), (28, w28_10), (28, w28_11), (28, w28_12), (28, w28_13), (28, w28_14), (28, w28_15), (28, w28_16), (28, w28_17), (28, w28_18), (28, w28_19), (29, w29_1), (29, w29_2), (29, w29_3), (29, w29_4), (29, w29_5), (29, w29_6), (29, w29_7)]

/-- Every census witness has a non-log-concave yet unimodal
independence polynomial. -/
theorem all_witnesses_nlc_unimodal :
    allWitnesses.all (fun t =>
      hasLCFailure (indepPoly t.1 t.2) && isUnimodal (indepPoly t.1 t.2)) = true := by
  decide

end Erdosattack
